### ISSUE TITLE
Display weather data of a particular searched city

### ISSUE THREAD

**Issue by infern018** [GeekHaven/weather-app#10]
In the Search route, display basic weather details of a city which will be accessed through the search from like: 
- temp
- temp_min & temp_max
- humidity
- wind->speed

look the API for the format

**Comment by kumarmanish03** [comment]
Can u assign me to this?

**Comment by garvitchittora** [comment]
@kumarmanish03 go ahead

**Comment by infern018** [comment]
@kumarmanish03  updates?

**Comment by Ranveer251** [comment]
can I give it a try?

**Comment by kumarmanish03** [comment]
I am working on it

**Comment by infern018** [comment]
@kumarmanish03  finish this by 3pm today else you will be unassigned

**Comment by infern018** [comment]
@Ranveer251  do you want to work on this?

**Comment by Ranveer251** [comment]
Yes
