### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by infern018** [GeekHaven/weather-app#12]
add a footer including social handle of this repo and the API with a meaningful message

**Comment by cosmoimai** [comment]
@infern018  can I work on this

**Comment by infern018** [comment]
Go for it

**Comment by cosmoimai** [comment]
API with meaningful messages what it means?

**Comment by infern018** [comment]
it's the link of this repo and the link of API and also a meaningful message for the footer

**Comment by cosmoimai** [comment]
I mean can please give the example of messages.

**Comment by infern018** [comment]
upto your creativity @cosmoimai  :P

**Comment by cosmoimai** [comment]
when I am trying to push it. It is showing permission denied

**Comment by garvitchittora** [comment]
you fork right?

**Comment by cosmoimai** [comment]
yes

**Comment by garvitchittora** [comment]
try [this](https://stackoverflow.com/questions/2643502/how-to-solve-permission-denied-publickey-error-when-using-git)
