### ISSUE TITLE
Create django Model

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#15]
Create a Django model name "User" in the Django app named "Subscribe" which contains fields like "email", "city" and "name".

**Comment by Capt-Titanium** [comment]
@garvitchittora , can i work on this issue?

**Comment by garvitchittora** [comment]
@Capt-Titanium sure.

**Comment by infern018** [comment]
@Capt-Titanium  updates?

**Comment by Capt-Titanium** [comment]
Sorry, I was working on another issue. Will do it by the end of the day for sure.
