### ISSUE TITLE
Get data from API

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#2]
Website = https://openweathermap.org/api
Get data from Open Weather Map and display it on Home page.

**Comment by somstrom** [comment]
@garvitchittora

Could you please assign this to me ?

**Comment by alkatrivedi** [comment]
I would like to work on this issue

**Comment by 2802harsh** [comment]
I want to work on this

**Comment by prince-7** [comment]
I would like  to work on this

**Comment by garvitchittora** [comment]
@2802harsh go ahead 🎉🎉.

**Comment by 2802harsh** [comment]
Working on it
