### ISSUE TITLE
Improve the overall UI of WebApp

### ISSUE THREAD

**Issue by infern018** [GeekHaven/weather-app#22]
currently no component is in order in the home page:
![screencapture-localhost-3000-2020-10-13-10_52_04](https://user-images.githubusercontent.com/52378712/95818803-57faf800-0d42-11eb-8fc7-b7b90a9f3055.png)
fix the navbar and include the heading in the navbar(you may remove the subheading), and maintain a fix color scheme for the home page including the footer :
Take inspiration from this : https://dribbble.com/shots/14267126-Travel-Landing-Page-UX-UI-Design

**Comment by kumarmanish03** [comment]
hey, I want to work on this

**Comment by infern018** [comment]
@kumarmanish03  first solve the prior issue that you're assigned

**Comment by sandy9808** [comment]
can we use material ui ?

**Comment by garvitchittora** [comment]
@sandy9808 go ahead :), you can use material UI, bootstrap, Bulma anything.

**Comment by sandy9808** [comment]
> @sandy9808 go ahead :), you can use material UI, bootstrap, Bulma anything.

Didn't started yet,  it would be good if this task is broken to small tasks like,
- design header in material ui
- design footer in material ui
- design homepage in material ui
- design search page in material ui
- design subscribe page in material ui

**Comment by garvitchittora** [comment]
bro @sandy9808, we should also focus on the quality of the issue then the number of issues solved 🤔.

**Comment by sandy9808** [comment]
> bro @sandy9808, we should also focus on the quality of the issue then the number of issues solved 🤔.

I am not a pro in material ui, it will take time to do all of this. That's why i was suggesting this.

**Comment by infern018** [comment]
@sandy9808 are you working on this?

**Comment by sandy9808** [comment]
> @sandy9808 are you working on this

Not started yet, will start by 8.

**Comment by infern018** [comment]
@sandy9808  remove the header if you want and import a navbar from material UI and change the color of footer too...

**Comment by infern018** [comment]
@sandy9808 updates?

**Comment by sandy9808** [comment]
Header : 
![image](https://user-images.githubusercontent.com/58395595/96117265-72320300-0f07-11eb-98aa-49d7ac3f4504.png)

![image](https://user-images.githubusercontent.com/58395595/96117309-85dd6980-0f07-11eb-8bf0-9e470a598d28.png)

Footer : 
Not complete yet.
![image](https://user-images.githubusercontent.com/58395595/96117370-9e4d8400-0f07-11eb-877c-db443444750e.png)

![image](https://user-images.githubusercontent.com/58395595/96117414-b1605400-0f07-11eb-9d7a-17166faa2d9e.png)

**Comment by infern018** [comment]
good work, just remove the red color of footer, give it a shade of blue with the font color of contents in white

**Comment by infern018** [comment]
@sandy9808  can you make a PR of this by midnight?

**Comment by infern018** [comment]
@sandy9808  updates?
