### ISSUE TITLE
Implement graph

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#25]
Implement graph in reactJS with the data like temp vs date graph of the previous 5 days.

**Comment by prince-7** [comment]
I would like to work on this

**Comment by garvitchittora** [comment]
@prince-7 bro, I can assign you one issue at a time, so search or this issue?

**Comment by prince-7** [comment]
@garvitchittora then give me search issue

**Comment by 2802harsh** [comment]
I want to work on this

**Comment by 2802harsh** [comment]
@garvitchittora Please Review the PR

**Comment by 2802harsh** [comment]
@garvitchittora I have made the final changes. Please review the PR.
