### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#3]
Add search page ("/search") , which contain search form.

**Comment by alkatrivedi** [comment]
I would like to work on it

**Comment by 2802harsh** [comment]
I want to work on this

**Comment by AlacritousCreature** [comment]
I want to work on this. May I?

**Comment by IC1101Virgo** [comment]
I would like to work on this. :)

**Comment by garvitchittora** [comment]
@AlacritousCreature  🎉🎉 go ahead with this one, @2802harsh @alkatrivedi has already an issue assigned in this repo. please complete that first, we have many more issues to come for all of you, I hope you both are fine with this.

**Comment by AlacritousCreature** [comment]
Thanks!

**Comment by garvitchittora** [comment]
hey, the issue will be unassigned if the assigned person is not able to solve it in 2 days so keep be quick :) .

**Comment by infern018** [comment]
@AlacritousCreature  updates??

**Comment by AlacritousCreature** [comment]
yeah I am working on same...I'll put it in just 15mins....sorry to respond late!

**Comment by AlacritousCreature** [comment]
Hey! @garvitchittora, @infern018 I have added the search form. Please review it, and let me know if is something wrong.
