### ISSUE TITLE
link logo to home page

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#31]
Link this logo in the header to the home page.

![Screenshot (397)_LI](https://user-images.githubusercontent.com/54021348/96253626-95c18000-0fd1-11eb-95a9-838adeda931d.jpg)

**Comment by sandy9808** [comment]
Then home icon should be removed?

**Comment by sandy9808** [comment]
i can do it

**Comment by shahidsiddiqui786** [comment]
I want do it,  please assign me
