### ISSUE TITLE
Fix location rendering in home page

### ISSUE THREAD

**Issue by infern018** [GeekHaven/weather-app#33]
<img width="949" alt="issue#1" src="https://user-images.githubusercontent.com/52378712/96253917-0ec0d780-0fd2-11eb-9100-836c992a4486.png">
Current  location is not being displayed in the home page, some component is not rendering, fix it

**Comment by sandy9808** [comment]
Limit is crossed i think. 
![image](https://user-images.githubusercontent.com/58395595/96255410-7ed05d00-0fd4-11eb-93cc-22861fc09ffd.png)
