### ISSUE TITLE
Add Browser Notifications

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#37]
Add Browser Notifications to this React App for now just the "Hello World" message.

**Comment by IC1101Virgo** [comment]
Claim

**Comment by garvitchittora** [comment]
@IC1101Virgo, PR for this issue is not correct, change it.

**Comment by prince-7** [comment]
I would like to work on this.

**Comment by garvitchittora** [comment]
@prince-7 go ahead 👍
