### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#4]
Add home page with containing weather app details

**Comment by dfoltynski** [comment]
Can u assign me to this? 😊

**Comment by infern018** [comment]
hey @dfoltynski actually it's part of a our college event, hence only the same students are allowed to contribute...

**Comment by dfoltynski** [comment]
hm, you can not tell them, that's a way out!

**Comment by thesmallstar** [comment]
> hm, you can not tell them, that's a way out!

Hey, thanks for your interest, we will notify you once we start accepting contributions on this. For now we are still figuring out some things before we can start.

-Thanks
Manthan

**Comment by infern018** [comment]
Don't forget to attach a screenshot of your changes in the PR

**Comment by alkatrivedi** [comment]
Can I take up the issue?

**Comment by infern018** [comment]
go for it..

**Comment by alkatrivedi** [comment]
On it. Thanks!

**Comment by alkatrivedi** [comment]
Can you please elaborate more? I am not getting what do you exactly mean by weather app details.

**Comment by infern018** [comment]
Add a heading and some description about the app on the home page, and try to add some images or  SGVs also for styling

**Comment by garvitchittora** [comment]
hey, the issue will be unassigned if the assigned person is not able to solve it in 2 days so keep be quick :) .

**Comment by alkatrivedi** [comment]
Yeah, I am working on it.

**Comment by alkatrivedi** [comment]
I have added a header check if it's ok or not.
![Capture](https://user-images.githubusercontent.com/58396306/95685860-26860d80-0c18-11eb-9c29-130717504672.JPG)

I am trying to add relevant image also. Will tell you the updates when done.

**Comment by garvitchittora** [comment]
nice, add one logo (take any general image) in the header and one image in the body.

**Comment by alkatrivedi** [comment]
Yeah doing!

**Comment by alkatrivedi** [comment]
I have added the image.
![Capture](https://user-images.githubusercontent.com/58396306/95689706-3dd0f500-0c30-11eb-9b18-20096c9e959e.JPG)

Check if the improvement is needed or not!

**Comment by infern018** [comment]
@alkatrivedi remove the background images, just go with the plain background

**Comment by alkatrivedi** [comment]
Okay so final would be like: 
![Capture](https://user-images.githubusercontent.com/58396306/95705615-40ecd500-0c72-11eb-81b7-2f2574ed2b0a.JPG)
