### ISSUE TITLE
Implement Routes

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#6]
## Implement the mentioned routes with some dummy components 
"/search" , "/subscribe" , "/current-location"

**Comment by sandy9808** [comment]
I will do it.

**Comment by infern018** [comment]
@sandy9808  the event will begin at midnight today, we will be assigning the issues from then onwards...

**Comment by 2802harsh** [comment]
I want to work on this

**Comment by 2802harsh** [comment]
Please review the PR [here](https://github.com/GeekHaven/weather-app/pull/7)
