### ISSUE TITLE
Send Email Form on subscribe page

### ISSUE THREAD

**Issue by garvitchittora** [GeekHaven/weather-app#8]
## Send Email Form
Send email form on subscribe page

**Comment by sandy9808** [comment]
Please assign me this task.

**Comment by garvitchittora** [comment]
Hey @sandy9808, thanks for your interest in this repo bit this repo is part of an event being held exclusively for our organization/college.

**Comment by sandy9808** [comment]
Same college bruh...

**Comment by infern018** [comment]
@sandy9808  go for it then :P

**Comment by sandy9808** [comment]
Can you please elaborate what i have to do in this subscribe page ?

**Comment by infern018** [comment]
just create a form that takes user's name and email with a submit button and proper styling

**Comment by garvitchittora** [comment]
@sandy9808 what is your progress now?

**Comment by sandy9808** [comment]
@garvitchittora Done....
[live link](https://jovial-fermat-89e37b.netlify.app)
Please review
